Landed initial fix for passing '\!' to script.

diff --git a/bnr b/bnr
--- a/bnr
+++ b/bnr
@@ -617,49 +617,52 @@ create_backup(){
 	    log_msg -e --msg="$msg"
 	    exit 1
 	fi
-	#if a mirroring was requested and a src file path is also present
-	if [ "$src_file_name" != '!' ]; then
-	    local expanded_tilde_prefix=
-	    local relative_backup_path=
-	    if [ "$MIRROR_FLG" -eq 1 ]; then
-		if [ "$tilde_expanded" -eq 1 ]; then
-		    expanded_tilde_prefix="$expanded_file_path_tilde_prefix"
-		    relative_backup_path="$src_file_name"
-		elif [ "$tilde_expanded" -eq 0 ]; then
-		    #we also try to remove direct references to values that would've been same as
-		    #a tilde expansion from the given source file name
-		    expanded_tilde_prefix="$(bash_helper_scripts/safe_tilde_expansion.sh "~")"
-		    #if the src_file_name is relative to /, then we get the rest of the path to make
-		    #it relative to the backup dir
-		    local allbutfirst="${src_file_name#?}"
-		    if [ "${src_file_name%"$allbutfirst"}" == '/' ]; then
-			relative_backup_path="${src_file_name#?}"
-		    else
-			relative_backup_path="$backup_file_name"
+
+	if [ "$backup_file_name" != '!' ]; then
+	    #if a mirroring was requested and a src file path is also present
+	    if [ "$src_file_name" != '!' ]; then
+		local expanded_tilde_prefix=
+		local relative_backup_path=
+		if [ "$MIRROR_FLG" -eq 1 ]; then
+		    if [ "$tilde_expanded" -eq 1 ]; then
+			expanded_tilde_prefix="$expanded_file_path_tilde_prefix"
+			relative_backup_path="$src_file_name"
+		    elif [ "$tilde_expanded" -eq 0 ]; then
+			#we also try to remove direct references to values that would've been same as
+			#a tilde expansion from the given source file name
+			expanded_tilde_prefix="$(bash_helper_scripts/safe_tilde_expansion.sh "~")"
+			#if the src_file_name is relative to /, then we get the rest of the path to make
+			#it relative to the backup dir
+			local allbutfirst="${src_file_name#?}"
+			if [ "${src_file_name%"$allbutfirst"}" == '/' ]; then
+			    relative_backup_path="${src_file_name#?}"
+			else
+			    relative_backup_path="$backup_file_name"
+			fi
+			unset allbutfirst
 		    fi
-		    unset allbutfirst
+	 	    local path_without_tilde_expansion="${relative_backup_path#"$expanded_tilde_prefix"'/'}"
+		    backup_file_name="$BACKUP_DIR"'/'"$path_without_tilde_expansion"
+		else
+		    backup_file_name="$BACKUP_DIR"'/'"$backup_file_name"
 		fi
-	 	local path_without_tilde_expansion="${relative_backup_path#"$expanded_tilde_prefix"'/'}"
-		backup_file_name="$BACKUP_DIR"'/'"$path_without_tilde_expansion"
 	    else
 		backup_file_name="$BACKUP_DIR"'/'"$backup_file_name"
 	    fi
-	else
-	    backup_file_name="$BACKUP_DIR"'/'"$backup_file_name"
-	fi
-	#msg="$(printf "Backup file path is %s\n\n" "$backup_file_name")"
-	#log_msg --msg="$msg"
-	#continue
+	    #msg="$(printf "Backup file path is %s\n\n" "$backup_file_name")"
+	    #log_msg --msg="$msg"
+	    #continue
 
-	#create the relative backup directory(ies) if it doesn't exist yet	
-	local backup_dir="$(dirname "$backup_file_name")"
-	if ! [ -d "$backup_dir" ]; then
-	    result="$(mkdir -p "$backup_dir" 2>&1)"
-	    if [ $? -ne 0 ]; then
-		msg="$(printf "Creating directory \"%s\" failed with error: %s" "$backup_dir" "$result")"
-		log_msg -e --msg="$msg"
-		create_log 0 0 "$index"
-		continue
+	    #create the relative backup directory(ies) if it doesn't exist yet	
+	    local backup_dir="$(dirname "$backup_file_name")"
+	    if ! [ -d "$backup_dir" ]; then
+		result="$(mkdir -p "$backup_dir" 2>&1)"
+		if [ $? -ne 0 ]; then
+		    msg="$(printf "Creating directory \"%s\" failed with error: %s" "$backup_dir" "$result")"
+		    log_msg -e --msg="$msg"
+		    create_log 0 0 "$index"
+		    continue
+		fi
 	    fi
 	fi
 	
